with-expecter: true
outpkg: "mocks"
dir: "{{.InterfaceDir}}/mocks/"
mockname: "Fake{{.InterfaceName}}"
filename: "{{.InterfaceName | snakecase}}.gen.go"

# Flags for future v3 compatibility.
# See https://github.com/vektra/mockery/issues/848
issue-845-fix: true
resolve-type-alias: false

packages:
  github.com/tbe-team/raybot/internal/services/command:
    config:
    interfaces:
      Service:
      ExecutorService:
      RunningCommandRepository:
      Repository:
      ProcessingLock:
  github.com/tbe-team/raybot/internal/services/drivemotor:
    config:
    interfaces:
      Service:
  github.com/tbe-team/raybot/internal/services/liftmotor:
    config:
    interfaces:
      Service:
  github.com/tbe-team/raybot/internal/services/cargo:
    config:
    interfaces:
      Service:
  github.com/tbe-team/raybot/internal/services/limitswitch:
    config:
    interfaces:
      Service:
  github.com/tbe-team/raybot/internal/services/config:
    config:
    interfaces:
      Service:
  github.com/tbe-team/raybot/internal/services/dashboarddata:
    config:
    interfaces:
      Service:
  github.com/tbe-team/raybot/internal/services/distancesensor:
    config:
    interfaces:
      Service:
  github.com/tbe-team/raybot/internal/services/apperrorcode:
    config:
    interfaces:
      Service:
  github.com/tbe-team/raybot/internal/services/peripheral:
    config:
    interfaces:
      Service:
  github.com/tbe-team/raybot/internal/services/system:
    config:
    interfaces:
      Service:
  github.com/tbe-team/raybot/pkg/eventbus:
    config:
    interfaces:
      Publisher:
