log:
  file:
    enable: false
    path: logs/raybot.log
    rotation_count: 2
    format: JSON
    level: ERROR
  console:
    enable: true
    format: TEXT
    level: DEBUG
hardware:
  esp:
    serial:
      port: /dev/ttyUSB0
      baud_rate: 9600
      data_bits: 8
      stop_bits: 1
      parity: NONE
      read_timeout: 1s
    enable_ack: false
    command_ack_timeout: 1s
  pic:
    serial:
      port: /dev/ttyUSB1
      baud_rate: 9600
      data_bits: 8
      stop_bits: 1
      parity: NONE
      read_timeout: 1s
    enable_ack: false
    command_ack_timeout: 1s
  leds:
    system:
      pin: 57
    alert:
      pin: 58
cloud:
  enable: false
  address: localhost:50051
  token: 4d24e88b41374b34a54806c0124b4052
http:
  swagger: true
  port: 3000
wifi:
  ap:
    enable: false
    ssid: Raybot AP
    password: "1111111"
    ip: 192.168.1.1
  sta:
    enable: false
    ssid: ssid
    password: password
    ip: 192.168.1.100/24
cron:
  delete_old_command:
    schedule: "@every 1h"
    threshold: 168h   # 7 days
command:
  cargo_lift:
    stable_read_count: 3
  cargo_lower:
    stable_read_count: 3
    bottom_obstacle_tracking:
      enter_distance: 20
      exit_distance: 30
monitoring:
  battery:
    voltage_low:
      enable: false
      threshold: 14
    voltage_high:
      enable: false
      threshold: 18
    cell_voltage_high:
      enable: false
      threshold: 4.3
    cell_voltage_low:
      enable: false
      threshold: 3.8
    cell_voltage_diff:
      enable: false
      threshold: 0.5
    current_high:
      enable: false
      threshold: 6
    temp_high:
      enable: false
      threshold: 60
    percent_low:
      enable: false
      threshold: 20
    health_low:
      enable: false
      threshold: 60
